### ISSUE TITLE
v0.2.2 checklist

### ISSUE THREAD

**Issue by that-hatter** [ProjectIgnis/scrapiyard#1]
progress is in [the 0.2.2 branch](/that-hatter/scrapiyard/tree/0.2.2-prerelease)
- [x] add inspiration/reference projects to the README
- [x] add pipeline guide to the README
- [x] fix the extended Reader module export
- [x] make sure string numbers are converted when parsing
- [x] remove test entry leftovers
- [x] add 80 character limit to summary and status.message
- [x] ~~remove the deasync import workaround~~ would unnecessarily complicate the markdown parse functions by having them return a `Task`
- [x] investigate if the bigint JSON.stringify workaround can be removed
   https://github.com/gcanti/io-ts/issues/648
- [x] add repository goals, non-goals, and limitations in the README
- [x] add specs and doc editing/adding guide
- [x] don't memoize markdown parsing
- [x] move /docs to ~~/entries~~ /api, and reorganize readme into smaller files
